name: Deploy to BinTray

on:
  release:
    types:
      - published
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@master
      with:
        ref: 'master'
    
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' 

    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Sync Submodules
      run: git submodule sync --recursive && git submodule update --recursive --init
          
    - name: Push to BinTray
      working-directory: ./MobileBuy
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      run: |
        set -eo pipefail
        echo "bintray.user=$BINTRAY_USER" >> local.properties
        echo "bintray.apikey=$BINTRAY_KEY" >> local.properties
        ./gradlew :buy3:bintrayUpload

