name: Create GitHub Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Draft Release
        uses: actions/github-script@0.9.0
        with:
          script: |
            const today = new Date();
            const yyyy = today.getFullYear();
            const mm = String(today.getMonth() + 1).padStart(2, '0');
            const api_version = yyyy + '-' + mm;
            github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "X.X.X",
              body: "Release notes:" +
                "\n- https://shopify.dev/concepts/about-apis/versioning/release-notes/" + api_version + "#storefront-api-changes",
              tag_name: 'x.x.x',
              target_commitish: 'master',
              draft: true,
              prerelease: false,
            })
